// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4K4tEPW0bTPSKqsMTxzSmny6Un9DGDX0',
    appId: '1:525840465634:web:853c7dc4ccf6be844ce8bb',
    messagingSenderId: '525840465634',
    projectId: 'mawjood-85dea',
    authDomain: 'mawjood-85dea.firebaseapp.com',
    storageBucket: 'mawjood-85dea.firebasestorage.app',
    measurementId: 'G-T7ZTHZTF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOKx_0OF0JLLnreTrx8T4HaxwkRzWuL4',
    appId: '1:525840465634:android:0664612b496dafc14ce8bb',
    messagingSenderId: '525840465634',
    projectId: 'mawjood-85dea',
    storageBucket: 'mawjood-85dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW5ouyDBq5ZbmQ8y2PVS1tClhfDsVbCOQ',
    appId: '1:525840465634:ios:619852b9f540dde14ce8bb',
    messagingSenderId: '525840465634',
    projectId: 'mawjood-85dea',
    storageBucket: 'mawjood-85dea.firebasestorage.app',
    iosBundleId: 'com.example.mawjood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW5ouyDBq5ZbmQ8y2PVS1tClhfDsVbCOQ',
    appId: '1:525840465634:ios:619852b9f540dde14ce8bb',
    messagingSenderId: '525840465634',
    projectId: 'mawjood-85dea',
    storageBucket: 'mawjood-85dea.firebasestorage.app',
    iosBundleId: 'com.example.mawjood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4K4tEPW0bTPSKqsMTxzSmny6Un9DGDX0',
    appId: '1:525840465634:web:28bf7833188cab464ce8bb',
    messagingSenderId: '525840465634',
    projectId: 'mawjood-85dea',
    authDomain: 'mawjood-85dea.firebaseapp.com',
    storageBucket: 'mawjood-85dea.firebasestorage.app',
    measurementId: 'G-GXJ7F4W3R2',
  );
}
